### PR TITLE
story/WOR-35/creer-le-model-de-donnee-routes-pour-les-conferences

### PR DESCRIPTION
**Pull request by remirubis**
## Description

This PR introduces new features and refactorings. Among the changes are the creation of a new model and tests for talk functionality, as well as the addition of new fields to the talk model to support editing. We've also added a new patch route to allow users to update talks and a new speaker route to fetch specific speaker information. We refactored several areas of the codebase to improve performance and maintainability, including adding mock returns values and new test cases for the speaker functionality.

## Changes

- Created talk model
- Created tests for `talks` TDD
- Added new fields to talk model for support editing
- Added patch route to update talks
- Added speaker route to fetch specific speaker information
- Refactored code for improved performance and maintainability
- Set function to test if error response feature to mocks
- Removed unnecessary imports in user tests
- Adapted and edited test cases for talk and speaker functionality

#### `POST` /talk - **ADMIN**

Create a new conference

#### `GET` /talk/:talkId - Available for disconnected users

Get a specific conference

#### `GET` /talks - Available for disconnected users

List all conferences

#### `PATCH` /talk/:talkId - **ADMIN**

Edit a specific conference

#### `DELETE` /talks - **ADMIN**

Delete a conference with his id

#### `GET` /speaker/:speakerId - Available for disconnected users

Get specific speaker with non-sensitive data

### CODE REVIEW

**Review by Maengdok — DISMISSED** [review]
👌🏻

**Review by kilianpichard — DISMISSED** [review]
Nice job !

**Review by Maengdok — COMMENTED** [review]
LGBTQ+

**Review by Maengdok — APPROVED** [review]
LGBTQ+A

**Review by kilianpichard — APPROVED** [review]

**Pull request merged**
