### PR TITLE
story/WOR-11/verification-du-numero-de-ticket-cote-api

### PR DESCRIPTION
**Pull request by remirubis**
## Description

I have added the entrance ticket management feature to Vivatech within the REST API. With this new feature, users can now purchase tickets for the event, and the system will manage the ticket's validity period, user information, and other details. It's just a mock of a potential implementation in vivatech api for internal usage.

## Changes

- Created a new User model.
- Set up the UserController to handle requests related to users.
- Added necessary packages and configured the environment for the user feature.
- Added routes for handling CRUD operations on users.
- Added tests to verify that all routes are working correctly.

### CODE REVIEW

**Review by kilianpichard — DISMISSED** [review]
LGTM !

**Review by BrystoQ — CHANGES_REQUESTED** [review]
LGTM ! Juste pour tous les Promise<void> dans le fichier ticket.controller.ts c'est dommage de typer en void et non vers la réponse attendu (ticket or null)

**Review by BrystoQ — APPROVED** [review]
LGTM !

**Review by kilianpichard — APPROVED** [review]
lgtm !

**Pull request merged**
